### ISSUE TITLE
Does not support quotes in urls in css

### ISSUE THREAD

**Issue by 0xR** [aruntk/wc-loader#13]
Code like this is not supported:
```css
  @font-face {
    font-family: "MyFont";
    src: url("MyFont.woff");
  }
```

It results in this error:

```
Module not found: Error: Can't resolve './"MyFont.woff"' in 'some/dir/on/machine'
```

Seems like a quick fix in processStyles.
