### ISSUE TITLE
ModuleNotFoundError with css external assets. How to handle css assets?

### ISSUE THREAD

**Issue by equinusocio** [aruntk/wc-loader#27]
Hi, i have this css snippet inside my web component:

```css
:host {
  display: flex;
  contain: content;
  position: relative;
  overflow: hidden;
  background-image: url("/assets/images/thread-row-placeholder.svg");
}
```

I get this error:
```
Module not found: Error: Can't resolve '/assets/images/thread-row-placeholder.svg'
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve '/assets/images/thread-row-placeholder.svg'
```

How do you suppose to handle external assets in css?

Atm i have to comment out this portion of the lib to get things work.
```js
var processed = text.replace(/url\(["']?((?!.*:\/\/|"|'|\)).+?)["']?\)/ig, function (_u, url) {
    // to get -> filepath from url(filepath), url('filepath') and url('filepath')
    return 'url(' + self._changeRelUrl(url, _path2.default.dirname(cssBasePath)) + ')';
});
return processed;
```

I'm on `webpack 3.4.1` and `wc-loader 1.1.9`

**Comment by aruntk** [comment]
@equinusocio try using `assets/` instead of `/assets/`. Latter one refers to assets folder inside your root folder. As the error suggests webpack could not resolve the absolute path `/assets/images/thread-row-placeholder.svg`. 

Or use absolute path to svg file. `/path/to/assets/`. 

```css
:host {
  display: flex;
  contain: content;
  position: relative;
  overflow: hidden;
  background-image: url("assets/images/thread-row-placeholder.svg");
}
```

Refer the example here https://github.com/aruntk/polymer-webpack-demo/blob/master/src/components/example-app.html#L25

Dont forget to define image loaders in your webpack config. eg https://github.com/aruntk/polymer-webpack-demo/blob/master/webpack.config.js#L22-L28
