### ISSUE TITLE
style tags are not handled properly

### ISSUE THREAD

**Issue by vehsakul** [aruntk/wc-loader#7]
This code fails
```js
case 'style':
            {
              if (child.childNodes && child.childNodes.length) {
                var childNode = child.childNodes[0];
                var css = childNode.value;
                var _result = self.processStyle(css);
                if (_result) {
                  childNode.value = _result;
                }
              }
              return child;
            }
```
processStyles takes 2 argumens, so the second is `undefined` and gets passed to `path.dirname` which fails in recent versions of node.

Won't the code replacing urls in styles break anything? E.g. I have the following. 
```css
      .number text.clipped {
        z-index: 4;
        fill: var(--text-primary-color);
        clip-path: url('#handClip');
      }
``` 
What is the expected behavior?
